services:
  farm:
    build:
      context: ./server
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server/app:/app
      - ./vol/sqlite:/app/data
    environment:
      CELERY_BROKER_URL: 'filesystem:///app/data/celery'
      SQLITE_DB_PATH: '/app/data/farm.db'
      SERVER_PASSWORD: ${SERVER_PASSWORD}
    restart: unless-stopped

  celery:
    build:
      context: ./server
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - ./server/app:/app
      - ./vol/sqlite:/app/data
    environment:
      CELERY_BROKER_URL: 'filesystem:///app/data/celery'
      SQLITE_DB_PATH: '/app/data/farm.db'
    restart: unless-stopped

  front:
    build:
      context: ./server
      dockerfile: ./docker/front/Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=http://farm:5000/api
    restart: unless-stopped
    ports:
      - "5137:3000"
    depends_on:
      - farm
      - celery