services:
  farm:
    build:
      context: ./server
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./server/app:/app
      - ./vol/sqlite:/app/data
    environment:
      CELERY_BROKER_URL: 'filesystem:///app/data/celery'
      SQLITE_DB_PATH: '/app/data/farm.db'
      SERVER_PASSWORD: ${SERVER_PASSWORD}
    restart: unless-stopped

  celery:
    build:
      context: ./server
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - ./server/app:/app
      - ./vol/sqlite:/app/data
    environment:
      CELERY_BROKER_URL: 'filesystem:///app/data/celery'
      SQLITE_DB_PATH: '/app/data/farm.db'
    restart: unless-stopped

  front:
    build:
      context: ./server
      dockerfile: ./docker/front/Dockerfile
    restart: unless-stopped
    ports:
      - "5137:80"