[Interface]
PrivateKey = gC2h76wMh6Sby+u+emyklTKeCWORkKq9uRR0rwjz5m4=
Address = 10.200.50.10/32
DNS = 8.8.8.8

[Peer]
PublicKey = AxHEQyUvvjmaXJFu2KtsAw5vu3dTDFPKDx0rSCz5GAY=
AllowedIPs = 10.0.38.0/27
Endpoint = 34.142.244.133:51820
PersistentKeepalive = 20